version: '3.8'

services:
  core:
    build: ./core
    ports:
      - '80:8080'
    restart: always
    volumes:
      - ./core:/app

  client:
    build: ./client
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./client:/usr/src/app

volumes:
  tickethobe:
